export const ADD_TODOS = 'ADD_TODOS'
export const TOGGLE_TODOS = 'TOGGLE_TODOS'
export const REMOVE_TODOS = 'REMOVE_TODOS'

export const ACTIVE_TODOS = 'ACTIVE_TODOS'
export const ALL_TODOS = 'ALL_TODOS'
export const COMPLETE_TODOS = 'COMPLETE_TODOS'
export const REMOVE_COMPLETE_TODOS = 'REMOVE_COMPLETE_TODOS'
export const REMOVE_ACTIVE_TODOS = 'REMOVE_ACTIVE_TODOS'


